include: package:flutter_lints/flutter.yaml

linter:
  rules:
    directives_ordering: true
    prefer_single_quotes: true
    lines_longer_than_80_chars: true
    cancel_subscriptions: true
    unnecessary_getters_setters: true
    prefer_relative_imports: true
    prefer_adjacent_string_concatenation: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_brace_in_string_interps: true
    prefer_collection_literals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_function_literals_in_foreach_calls: true
    unnecessary_lambdas: true
    prefer_expression_function_bodies: true
    prefer_initializing_formals: true
    empty_constructor_bodies: true
    unnecessary_const: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    use_to_and_as_if_applicable: true
    one_member_abstracts: true
    avoid_classes_with_only_static_members: true
    prefer_final_fields: true
    use_setters_to_change_properties: true
    avoid_returning_this: true
    omit_local_variable_types: true
    avoid_types_on_closure_parameters: true
    type_init_formals: true
    prefer_generic_function_type_aliases: true
    avoid_private_typedef_functions: true
    avoid_positional_boolean_parameters: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
