name: mzflood
description: "A nicer, smoother implementation of the Flood Fill puzzle game from Simon Tatham's Portable Puzzle Collection"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_colorpicker: ^1.1.0
  collection: ^1.19.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_app_name_localization: ^0.0.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon.png

flutter_app_name_localization:
  default: "MZFlood"
  locales:
    - locale: "ru"
      name: "Заливка"

flutter_native_splash:
  android: true

  ios: false
  web: false

  color: "#f0f8ff"

  image: assets/images/app_icon.png

  android_12:
    image: assets/images/splash_icon_android12.png

    color: "#f0f8ff"

    icon_background_color: "#111111"

    color_dark: "#000000"
    icon_background_color_dark: "#eeeeee"
